repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.1.0
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: gofmt
      - id: goimports
      # Golint seems to be too strict with its validations: https://github.com/golang/lint/issues/389
      # - id: golint
